spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/batchdb
      username: sa
      password:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false